name: Run Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - fix/*
      - hotfix/*
      - refactor/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - fix/*
      - hotfix/*

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        dependencies: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, zip, curl, gd
          ini-values: |
            memory_limit=-1
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --no-suggest

      - name: Check code style with Laravel Pint
        run: |
          vendor/bin/pint --test

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse config src tests --memory-limit=1G --level=7

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit --configuration phpunit.xml
