name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']
        dependencies: ['lowest', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, zip, curl, gd
          ini-values: |
            memory_limit=-1
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --${{ matrix.dependencies }} --no-progress --no-suggest --prefer-dist

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit --configuration phpunit.xml
